- name: Configuring the backend server
  hosts: backend
  become: yes
  tasks: 
  - name: disable nodejs current version
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable nodejs 20
    ansible.builtin.command: "dnf module enable nodejs:20 -y"
  
  - name: install nodejs 20
    ansible.builtin.package:
      name: nodejs
      state: present