- name: Configuring Frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  
  - name: enable and start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Removing default html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: downloading the frontend content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: Unzipping the frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: Copying the expense Config
    ansible.builtin.copy:
      src: /home/ec2-user/ansible_expense/expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Restart the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted